src/Requiem.FactsBlog/Requiem.Facts.Web/ViewModels/ErrorViewModel.cs
namespace Requiem.Facts.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/Requiem.FactsBlog/Requiem.Facts.Web/ViewModels/FactCreateViewModel.cs
namespace Requiem.Facts.Web.ViewModels;

public class FactCreateViewModel
{
    public string Content { get; set; }

    public IEnumerable<string> Tags { get; set; }
}

src/Requiem.FactsBlog/Requiem.Facts.Web/ViewModels/FactUpdateViewModel.cs
namespace Requiem.Facts.Web.ViewModels;
public class FactUpdateViewModel
{
    public Guid Id { get; set; }

    public string Content { get; set; }

    public IEnumerable<string> Tags { get; set; }
}

src/Requiem.FactsBlog/Requiem.Facts.Web/ViewModels/FactViewModel.cs
namespace Requiem.Facts.Web.ViewModels;

public class FactViewModel
{
    public Guid Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Content { get; set; } = null!;

    public IEnumerable<TagViewModel> Tags { get; set; } = null!;
}

src/Requiem.FactsBlog/Requiem.Facts.Web/ViewModels/TagUpdateViewModel.cs
namespace Requiem.Facts.Web.ViewModels;

public class TagUpdateViewModel
{
    public Guid Id { get; set; }

    public string Name { get; set; }
}

src/Requiem.FactsBlog/Requiem.Facts.Web/ViewModels/TagViewModel.cs
namespace Requiem.Facts.Web.ViewModels;

public class TagViewModel
{
    public Guid Id { get; set; }

    public string Name { get; set; }
}

src/Requiem.FactsBlog/Requiem.Facts.Web/Controllers/Facts/FactsController.cs
using Requiem.Facts.Web.Controllers.Facts.Queries;

namespace Requiem.Facts.Web.Controllers.Facts;

public class FactsController : Controller
{
    private readonly IMediator _mediator;
    public FactsController(IMediator mediator)
    {
        _mediator = mediator;
    }
    public async Task<IActionResult> Index(int? pageIndex, string tag, string search)
    {
        var operationResult = await _mediator.Send(new FactGetPagedRequest(pageIndex ?? 1, tag, search), HttpContext.RequestAborted);
        return View(operationResult);
    }
}

src/Requiem.FactsBlog/Requiem.Facts.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Requiem.Facts.Web.Models;
using System.Diagnostics;

namespace Requiem.Facts.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Requiem.FactsBlog/Requiem.Facts.Web/Controllers/SiteController.cs
using Requiem.Facts.Web.Models;
using Requiem.Facts.Web.Mediatr;

namespace Requiem.Facts.Web.Controllers;

public class SiteController : Controller
{
    private readonly IMediator _mediator;
    public SiteController(IMediator mediator)
    {
        _mediator= mediator;
    }
    

    public async Task<IActionResult> Privacy()
    {
        await _mediator.Publish(new ErrorNotification("Privacy test for notification"), HttpContext.RequestAborted);
        await _mediator.Publish(new FeedbackNotification("Helloyoursiteiscoolgood"), HttpContext.RequestAborted);
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Requiem.FactsBlog/Requiem.Facts.Web/Views/Facts/Index.cshtml
@model Calabonga.OperationResults.OperationResult<Calabonga.UnitOfWork.IPagedList<Requiem.Facts.Web.ViewModels.FactViewModel>>

@{
    Layout = "_LayoutColumn";
    ViewData["Title"] = "Home Page";
}

@if(Model is not null)
{
    foreach(var fact in Model.Result.Items)
    {
        <partial name="_Fact" model="fact"/>
        
    }

    <pager class="my-5" asp-paged-list-page-size="Model.Result.PageSize"
       asp-paged-list-total-count="Model.Result.TotalCount"
       asp-paged-list-page-index="Model.Result.PageIndex"
       asp-paged-list-url="index"
       asp-controller="facts"
       asp-route-parameter="pageIndex"></pager>
}

@section Column
{
    <div class="my-3">
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
}

src/Requiem.FactsBlog/Requiem.Facts.Web/Views/Facts/_Fact.cshtml
@model Requiem.Facts.Web.ViewModels.FactViewModel
<div class="card my-3">
    <div class="card-header">
        <div class="row">
            <div class="col">
                <div class="float-start">@Model.CreatedAt.ToString("d")</div>
            </div>
            <div class="col">
                <div class="float-end"><partial name="_FactsLink" model="Model.Id" /></div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col">
                <p class="lead">
                    @Model.Content
                </p>
                <p>
                    <partial name="_Tags" model="Model.Tags" />
                </p>
            </div>
        </div>
    </div>
</div>

src/Requiem.FactsBlog/Requiem.Facts.Web/Views/Facts/_FactsLink.cshtml
@model Guid

<a asp-controller="Facts" asp-action="" asp-route-id="@Model">Link</a>

src/Requiem.FactsBlog/Requiem.Facts.Web/Views/Facts/_Tags.cshtml
@model IEnumerable<Requiem.Facts.Web.ViewModels.TagViewModel>

@foreach(var tag in Model)
{
    <span class="badge bg-secondary">@tag.Name</span>
}

src/Requiem.FactsBlog/Requiem.Facts.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Requiem.Facts.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Requiem.Facts.Web.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Headers", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Site" asp-action="Index">Facts Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Site" asp-action="Index">Site</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Site" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <partial name="_LoginPartial" />
                    </ul>                   
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Site" asp-action="About">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Site" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                </li>
            </ul>
            <p class="text-center">
                &copy; 2022 - Requiem SOFT
            </p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Requiem.FactsBlog/Requiem.Facts.Web/Views/Shared/_LayoutColumn.cshtml
@{
    Layout = "_Layout";
}

<div class="row">
    <div class="col-md-9 col-sm-6">
        @RenderBody()
    </div>
    <div class="col-md-3 col-sm-6">
        @await RenderSectionAsync("Column", required: true)
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Consectetur libero id faucibus nisl tincidunt eget nullam non nisi.
            Adipiscing bibendum est ultricies integer. Non nisi est sit amet facilisis magna.
            Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean.
            Commodo quis imperdiet massa tincidunt nunc pulvinar.
            Pellentesque eu tincidunt tortor aliquam.
            Semper eget duis at tellus at urna condimentum mattis pellentesque.
            Eget egestas purus viverra accumsan in nisl nisi.
            Sed augue lacus viverra vitae congue eu consequat. 
            Dignissim cras tincidunt lobortis feugiat vivamus at augue eget.
        </p>
    </div>
</div>